export interface WordEntry {
  text: string
  emoji: string
}

export const WORD_BANK: Record<string, WordEntry[]> = {
  fr: [
    { text: "JÉSUS", emoji: "✝️" }, { text: "BIBLE", emoji: "📖" },
    { text: "AMOUR", emoji: "❤️" }, { text: "PAIX", emoji: "🕊️" },
    { text: "FOI", emoji: "🙏" }, { text: "ESPOIR", emoji: "⚓" },
    { text: "JOIE", emoji: "😊" }, { text: "LUMIÈRE", emoji: "💡" },
    { text: "VIE", emoji: "🌱" }, { text: "DIEU", emoji: "👑" },
    { text: "ESPRIT", emoji: "🔥" }, { text: "GRÂCE", emoji: "🎁" },
    { text: "PRIÈRE", emoji: "🧎" }, { text: "ÉGLISE", emoji: "⛪" },
    { text: "NOÉ", emoji: "🌈" }, { text: "ADAM", emoji: "👨" },
    { text: "ÈVE", emoji: "👩" }, { text: "MARIE", emoji: "🤱" },
    { text: "JOSEPH", emoji: "🔨" }, { text: "DAVID", emoji: "👑" },
    { text: "GOLIATH", emoji: "⚔️" }, { text: "MOÏSE", emoji: "🌊" },
    { text: "PAUL", emoji: "📜" }, { text: "PIERRE", emoji: "🪨" },
    { text: "JEAN", emoji: "🦅" }, { text: "LUC", emoji: "⚕️" },
    { text: "MARC", emoji: "🦁" }, { text: "MATTHIEU", emoji: "💰" },
    { text: "ESTHER", emoji: "👸" }, { text: "JONAS", emoji: "🐋" },
    { text: "TEMPLE", emoji: "🏛️" }, { text: "AUTEL", emoji: "🔥" },
    { text: "PAIN", emoji: "🍞" }, { text: "VIN", emoji: "🍷" },
    { text: "EAU", emoji: "💧" }, { text: "FEU", emoji: "🔥" },
    { text: "SAGESSE", emoji: "🧠" }, { text: "VÉRITÉ", emoji: "✅" },
    { text: "CHEMIN", emoji: "🛣️" }, { text: "PORTE", emoji: "🚪" },
    { text: "BERGER", emoji: "🐑" }, { text: "AGNEAU", emoji: "🐑" },
    { text: "LION", emoji: "🦁" }, { text: "ROCHER", emoji: "🪨" },
    { text: "ANGE", emoji: "👼" }, { text: "CIEL", emoji: "☁️" },
    { text: "CROIX", emoji: "✝️" }, { text: "ROI", emoji: "👑" },
    { text: "VIGNE", emoji: "🍇" }, { text: "POISSON", emoji: "🐟" },
    { text: "SEL", emoji: "🧂" }, { text: "LAMPE", emoji: "🕯️" },
    { text: "ARCHE", emoji: "⛵" }, { text: "LOI", emoji: "📜" },
    { text: "PAROLE", emoji: "🗣️" }, { text: "LOUANGE", emoji: "🙌" },
    { text: "SANG", emoji: "🩸" }, { text: "ENFANT", emoji: "👶" },
    { text: "FILS", emoji: "👦" }, { text: "FILLE", emoji: "👧" },
    { text: "FAMILLE", emoji: "👨‍👩‍👧" }, { text: "MAISON", emoji: "🏠" },
    { text: "MONDE", emoji: "🌍" }, { text: "JOUR", emoji: "☀️" },
    { text: "NUIT", emoji: "🌙" }, { text: "ÉTOILE", emoji: "⭐" },
    { text: "TRÔNE", emoji: "👑" }, { text: "ÉPÉE", emoji: "🗡️" },
    { text: "COLOMBE", emoji: "🕊️" }, { text: "AIGLE", emoji: "🦅" },
    { text: "FRUIT", emoji: "🍎" }, { text: "ARBRE", emoji: "🌳" },
    { text: "DANIEL", emoji: "🦁" }, { text: "DÉSERT", emoji: "🏜️" },
    { text: "MIEL", emoji: "🍯" }, { text: "SALOMON", emoji: "👑" },
    { text: "OR", emoji: "💍" }, { text: "GLOIRE", emoji: "👑" },
    { text: "AMEN", emoji: "🙏" }, { text: "SAINT", emoji: "😇" },
    { text: "SERPENT", emoji: "🐍" }, { text: "COLÈRE", emoji: "😤" },
    { text: "SEIGNEUR", emoji: "🤴" }, { text: "SAUVEUR", emoji: "🕊️" },
    { text: "MAÎTRE", emoji: "👑" }, { text: "LIBRE", emoji: "🆓" },
    { text: "CHANTER", emoji: "🎵" }, { text: "BÉNIR", emoji: "❤️" },
    { text: "DONNER", emoji: "🎁" }, { text: "CHERCHER", emoji: "🔎" },
    { text: "TROUVER", emoji: "💡" }, { text: "BON", emoji: "👍" },
    { text: "ABEL", emoji: "👨" }, { text: "APÔTRE", emoji: "📜" },
  ],
  en: [
    { text: "JESUS", emoji: "✝️" }, { text: "BIBLE", emoji: "📖" },
    { text: "LOVE", emoji: "❤️" }, { text: "PEACE", emoji: "🕊️" },
    { text: "FAITH", emoji: "🙏" }, { text: "HOPE", emoji: "⚓" },
    { text: "JOY", emoji: "😊" }, { text: "LIGHT", emoji: "💡" },
    { text: "LIFE", emoji: "🌱" }, { text: "GOD", emoji: "👑" },
    { text: "SPIRIT", emoji: "🔥" }, { text: "GRACE", emoji: "🎁" },
    { text: "PRAYER", emoji: "🧎" }, { text: "CHURCH", emoji: "⛪" },
    { text: "NOAH", emoji: "🌈" }, { text: "ADAM", emoji: "👨" },
    { text: "EVE", emoji: "👩" }, { text: "MARY", emoji: "🤱" },
    { text: "JOSEPH", emoji: "🔨" }, { text: "DAVID", emoji: "👑" },
    { text: "MOSES", emoji: "🌊" }, { text: "PAUL", emoji: "📜" },
    { text: "PETER", emoji: "🪨" }, { text: "JOHN", emoji: "🦅" },
    { text: "LUKE", emoji: "⚕️" }, { text: "MARK", emoji: "🦁" },
    { text: "ESTHER", emoji: "👸" }, { text: "JONAH", emoji: "🐋" },
    { text: "TEMPLE", emoji: "🏛️" }, { text: "BREAD", emoji: "🍞" },
    { text: "WATER", emoji: "💧" }, { text: "FIRE", emoji: "🔥" },
    { text: "WISDOM", emoji: "🧠" }, { text: "TRUTH", emoji: "✅" },
    { text: "SHEPHERD", emoji: "🐑" }, { text: "LAMB", emoji: "🐑" },
    { text: "ANGEL", emoji: "👼" }, { text: "HEAVEN", emoji: "☁️" },
    { text: "CROSS", emoji: "✝️" }, { text: "KING", emoji: "👑" },
    { text: "VINE", emoji: "🍇" }, { text: "FISH", emoji: "🐟" },
    { text: "SALT", emoji: "🧂" }, { text: "LAMP", emoji: "🕯️" },
    { text: "ARK", emoji: "⛵" }, { text: "LAW", emoji: "📜" },
    { text: "PRAISE", emoji: "🙌" }, { text: "BLOOD", emoji: "🩸" },
    { text: "CHILD", emoji: "👶" }, { text: "SON", emoji: "👦" },
    { text: "FAMILY", emoji: "👨‍👩‍👧" }, { text: "HOUSE", emoji: "🏠" },
    { text: "WORLD", emoji: "🌍" }, { text: "DAY", emoji: "☀️" },
    { text: "NIGHT", emoji: "🌙" }, { text: "STAR", emoji: "⭐" },
    { text: "SWORD", emoji: "🗡️" }, { text: "DOVE", emoji: "🕊️" },
    { text: "EAGLE", emoji: "🦅" }, { text: "FRUIT", emoji: "🍎" },
    { text: "TREE", emoji: "🌳" }, { text: "DANIEL", emoji: "🦁" },
    { text: "DESERT", emoji: "🏜️" }, { text: "HONEY", emoji: "🍯" },
    { text: "GOLD", emoji: "💍" }, { text: "GLORY", emoji: "👑" },
    { text: "AMEN", emoji: "🙏" }, { text: "HOLY", emoji: "😇" },
    { text: "LORD", emoji: "🤴" }, { text: "SAVIOR", emoji: "🕊️" },
    { text: "BLESSING", emoji: "❤️" }, { text: "SEEK", emoji: "🔎" },
    { text: "GOOD", emoji: "👍" }, { text: "ABEL", emoji: "👨" },
  ],
  pt: [
    { text: "JESUS", emoji: "✝️" }, { text: "BÍBLIA", emoji: "📖" },
    { text: "AMOR", emoji: "❤️" }, { text: "PAZ", emoji: "🕊️" },
    { text: "FÉ", emoji: "🙏" }, { text: "ESPERANÇA", emoji: "⚓" },
    { text: "ALEGRIA", emoji: "😊" }, { text: "LUZ", emoji: "💡" },
    { text: "VIDA", emoji: "🌱" }, { text: "DEUS", emoji: "👑" },
    { text: "ESPÍRITO", emoji: "🔥" }, { text: "GRAÇA", emoji: "🎁" },
    { text: "ORAÇÃO", emoji: "🧎" }, { text: "IGREJA", emoji: "⛪" },
    { text: "NOÉ", emoji: "🌈" }, { text: "ADÃO", emoji: "👨" },
    { text: "EVA", emoji: "👩" }, { text: "MARIA", emoji: "🤱" },
    { text: "JOSÉ", emoji: "🔨" }, { text: "DAVI", emoji: "👑" },
    { text: "MOISÉS", emoji: "🌊" }, { text: "PAULO", emoji: "📜" },
    { text: "PEDRO", emoji: "🪨" }, { text: "JOÃO", emoji: "🦅" },
    { text: "LUCAS", emoji: "⚕️" }, { text: "MARCOS", emoji: "🦁" },
    { text: "ESTER", emoji: "👸" }, { text: "JONAS", emoji: "🐋" },
    { text: "TEMPLO", emoji: "🏛️" }, { text: "PÃO", emoji: "🍞" },
    { text: "ÁGUA", emoji: "💧" }, { text: "FOGO", emoji: "🔥" },
    { text: "SABEDORIA", emoji: "🧠" }, { text: "VERDADE", emoji: "✅" },
    { text: "PASTOR", emoji: "🐑" }, { text: "CORDEIRO", emoji: "🐑" },
    { text: "ANJO", emoji: "👼" }, { text: "CÉU", emoji: "☁️" },
    { text: "CRUZ", emoji: "✝️" }, { text: "REI", emoji: "👑" },
    { text: "VIDEIRA", emoji: "🍇" }, { text: "PEIXE", emoji: "🐟" },
    { text: "SAL", emoji: "🧂" }, { text: "LÂMPADA", emoji: "🕯️" },
    { text: "ARCA", emoji: "⛵" }, { text: "LEI", emoji: "📜" },
    { text: "LOUVOR", emoji: "🙌" }, { text: "SANGUE", emoji: "🩸" },
    { text: "FILHO", emoji: "👦" }, { text: "FAMÍLIA", emoji: "👨‍👩‍👧" },
    { text: "CASA", emoji: "🏠" }, { text: "MUNDO", emoji: "🌍" },
    { text: "DIA", emoji: "☀️" }, { text: "NOITE", emoji: "🌙" },
    { text: "ESTRELA", emoji: "⭐" }, { text: "POMBA", emoji: "🕊️" },
    { text: "FRUTO", emoji: "🍎" }, { text: "ÁRVORE", emoji: "🌳" },
    { text: "DANIEL", emoji: "🦁" }, { text: "OURO", emoji: "💍" },
    { text: "GLÓRIA", emoji: "👑" }, { text: "AMÉM", emoji: "🙏" },
    { text: "SANTO", emoji: "😇" }, { text: "SENHOR", emoji: "🤴" },
    { text: "BÊNÇÃO", emoji: "❤️" }, { text: "BOM", emoji: "👍" },
  ],
  th: [
    { text: "พระเยซู", emoji: "✝️" }, { text: "พระคัมภีร์", emoji: "📖" },
    { text: "ความรัก", emoji: "❤️" }, { text: "สันติภาพ", emoji: "🕊️" },
    { text: "ความเชื่อ", emoji: "🙏" }, { text: "ความหวัง", emoji: "⚓" },
    { text: "ความยินดี", emoji: "😊" }, { text: "แสงสว่าง", emoji: "💡" },
    { text: "ชีวิต", emoji: "🌱" }, { text: "พระเจ้า", emoji: "👑" },
    { text: "พระวิญญาณ", emoji: "🔥" }, { text: "พระคุณ", emoji: "🎁" },
    { text: "การอธิษฐาน", emoji: "🧎" }, { text: "คริสตจักร", emoji: "⛪" },
    { text: "โนอาห์", emoji: "🌈" }, { text: "อาดัม", emoji: "👨" },
    { text: "เอวา", emoji: "👩" }, { text: "มารีย์", emoji: "🤱" },
    { text: "โยเซฟ", emoji: "🔨" }, { text: "ดาวิด", emoji: "👑" },
    { text: "โมเสส", emoji: "🌊" }, { text: "เปาโล", emoji: "📜" },
    { text: "เปโตร", emoji: "🪨" }, { text: "ยอห์น", emoji: "🦅" },
    { text: "เอสเธอร์", emoji: "👸" }, { text: "โยนาห์", emoji: "🐋" },
    { text: "วิหาร", emoji: "🏛️" }, { text: "ขนมปัง", emoji: "🍞" },
    { text: "น้ำ", emoji: "💧" }, { text: "ไฟ", emoji: "🔥" },
    { text: "ปัญญา", emoji: "🧠" }, { text: "ความจริง", emoji: "✅" },
    { text: "นายชุมแกะ", emoji: "🐑" }, { text: "ลูกแกะ", emoji: "🐑" },
    { text: "ทูตสวรรค์", emoji: "👼" }, { text: "สวรรค์", emoji: "☁️" },
    { text: "กางเขน", emoji: "✝️" }, { text: "กษัตริย์", emoji: "👑" },
    { text: "เถาองุ่น", emoji: "🍇" }, { text: "ปลา", emoji: "🐟" },
    { text: "เกลือ", emoji: "🧂" }, { text: "โคมไฟ", emoji: "🕯️" },
    { text: "เรือโนอาห์", emoji: "⛵" }, { text: "กฎหมาย", emoji: "📜" },
    { text: "การสรรเสริญ", emoji: "🙌" }, { text: "โลหิต", emoji: "🩸" },
    { text: "บุตร", emoji: "👦" }, { text: "ครอบครัว", emoji: "👨‍👩‍👧" },
    { text: "บ้าน", emoji: "🏠" }, { text: "โลก", emoji: "🌍" },
    { text: "วัน", emoji: "☀️" }, { text: "คืน", emoji: "🌙" },
    { text: "ดาว", emoji: "⭐" }, { text: "นกพิราบ", emoji: "🕊️" },
    { text: "ผลไม้", emoji: "🍎" }, { text: "ต้นไม้", emoji: "🌳" },
    { text: "ดาเนียล", emoji: "🦁" }, { text: "ทอง", emoji: "💍" },
    { text: "พระสิริ", emoji: "👑" }, { text: "อาเมน", emoji: "🙏" },
    { text: "บริสุทธิ์", emoji: "😇" }, { text: "พระเป็นเจ้า", emoji: "🤴" },
    { text: "พระพร", emoji: "❤️" }, { text: "ดี", emoji: "👍" },
  ],
}

export const ALPHABETS: Record<string, string[]> = {
  fr: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split(''),
  en: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split(''),
  pt: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split(''),
  th: 'กขคงจฉชซญดตถทนบปผฝพฟภมยรลวสหอ'.split(''),
}
